import React from "react";
import { useApp } from "../../context/AppContext";
import { Search, Trash2, ArrowRight } from "lucide-react";

export default function HistoryTab() {
  const { history, triggerAnalysis, deleteHistoryItem, clearHistory, loadReportById } = useApp();

  return (
    <div className="bg-card border border-border rounded-2xl p-6 transition-all duration-300 space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-base font-extrabold text-white">Research History</h3>
          <p className="text-[11px] text-text-secondary mt-0.5 font-medium">Browse historical stock analyses generated by the AI agent terminal.</p>
        </div>
        {history.length > 0 && (
          <button 
            onClick={clearHistory}
            className="text-[10px] text-red font-bold hover:underline cursor-pointer"
          >
            Clear History
          </button>
        )}
      </div>

      {history.length === 0 ? (
        <div className="py-16 text-center space-y-3 bg-muted/10 border border-dashed border-border/60 rounded-xl">
          <div className="w-10 h-10 rounded-full bg-muted border border-border flex items-center justify-center text-text-secondary mx-auto">
            <Search className="w-4.5 h-4.5" />
          </div>
          <div>
            <h4 className="text-xs font-bold text-white">No reports found.</h4>
            <p className="text-[10px] text-text-secondary mt-1">Every completed company analysis will appear here.</p>
          </div>
        </div>
      ) : (
        <div className="border border-border/40 rounded-xl overflow-hidden bg-muted/10">
          <div className="overflow-x-auto no-scrollbar">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-border/40 bg-muted text-text-secondary font-bold">
                  <th className="p-3">Company</th>
                  <th className="p-3">Ticker</th>
                  <th className="p-3">Analysis Date</th>
                  <th className="p-3">Score</th>
                  <th className="p-3">Recommendation</th>
                  <th className="p-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/20 text-text-secondary font-medium">
                {history.map((item) => (
                  <tr key={item.id} className="hover:bg-muted/10">
                    <td 
                      onClick={() => loadReportById(item.id)}
                      className="p-3 text-white font-bold cursor-pointer hover:underline"
                    >
                      {item.companyName}
                    </td>
                    <td className="p-3 font-mono">{item.ticker}</td>
                    <td className="p-3">{item.date}</td>
                    <td className="p-3 font-mono text-white font-bold">{item.investmentScore} / 100</td>
                    <td className="p-3">
                      <span className={`px-2 py-0.5 text-[10px] font-bold rounded-full border ${
                        item.recommendation.includes("Buy") 
                          ? "bg-green/10 text-green border-green/20" 
                          : item.recommendation.includes("Hold") 
                          ? "bg-orange/10 text-orange border-orange/20" 
                          : "bg-red/10 text-red border-red/20"
                      }`}>
                        {item.recommendation}
                      </span>
                    </td>
                    <td className="p-3 text-right flex justify-end gap-3">
                      <button 
                        onClick={() => loadReportById(item.id)}
                        className="text-primary hover:text-primary/80 font-bold flex items-center gap-1 cursor-pointer"
                      >
                        <span>Open Report</span>
                        <ArrowRight className="w-3.5 h-3.5" />
                      </button>
                      <button 
                        onClick={() => deleteHistoryItem(item.id)}
                        className="text-text-secondary hover:text-red p-1 rounded transition-colors cursor-pointer"
                        title="Delete record"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
